env:
  browser: true
  es2021: true
  jest: true
  jest/globals: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/all
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  ecmaFeatures:
    jsx: true
  sourceType: module
plugins:
  - react
  - react-hooks
  - '@typescript-eslint'
  - simple-import-sort
  - jest
  - prettier
ignorePatterns:
  - '**/*.d.ts'
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  require-unicode-regexp: off
  capitalized-comments: off
  react/jsx-no-literals: off
  react/jsx-max-depth: off
  react/jsx-filename-extension:
    - 1
    - extensions:
      - .tsx
  simple-import-sort/imports: error
  simple-import-sort/exports: error
  sort-imports: off
  one-var: off
  no-ternary: off
  # no-magic-numbers: off
settings:
  react:
    version: detect