#!/bin/bash

GHCP_DIR="../../../akseiya.github.io"

npm run build &
git add -A
git commit -F -
last_commit=`git log -1 --pretty=%B`
rm -rf "$GHCP_DIR"/static
wait
git push
cp -r build/* "$GHCP_DIR"
cd "$GHCP_DIR"
git add -A
git commit -m "$last_commit"
git push
