#!/bin/bash

die() {
    echo "$@" > /dev/stderr
    exit 1
}

cd "${0%/*}"
[ -f .env ] && source .env
echo "Usage target directory $ghpDir"

set -e

# GitHub Pages repo directory is required
[ "$ghpDir" ]
# Die if target dir not where expected
stat "$ghpDir" > /dev/null

git add -A
git commit -F -
last_commit=`git log -1 --pretty=%B`
git push

rm -rf "$ghpDir"/*
cp -r build/* "$ghpDir"

cd "$ghpDir"
git add -A
git commit -m "$last_commit"
git push

head -c 12 /dev/random | base64 > uniq.txt
git add -A
git commit -F - <<EOF
    Dummy commit to nudge gitHub Pages.
    Check out the previous commit:
    $last_commit
EOF
git push
