#!/bin/bash

die() {
    echo "$@" >&2
    exit 1
}

cd "${0%/*}"
[ -f .env ] && source .env
echo "Using target directory $GITHUB_PAGES_DIRECTORY"

set -e

# GitHub Pages repo directory is required
[ "$GITHUB_PAGES_DIRECTORY" ]
# Die if target dir not where expected
stat "$GITHUB_PAGES_DIRECTORY" > /dev/null

commit_current() {
    git add -A
    git commit -F -
}

[ "$(git status --porcelain | wc -c)" = "0" ] || commit_current
last_commit=`git log -1 --pretty=%B`
git status | grep -q 'Your branch is ahead' || git push

# Decide if you want auto-build.
npm run build
rm -rf "$GITHUB_PAGES_DIRECTORY"/*
cp -r build/* "$GITHUB_PAGES_DIRECTORY"

cd "$GITHUB_PAGES_DIRECTORY"
git add -A
git commit -m "$last_commit"
git push

# gitHub Pages just needs a bit of time.

# head -c 12 /dev/random | base64 > uniq.txt
# git add -A
# git commit -F - <<EOF
#     Dummy commit to nudge gitHub Pages.
#     Check out the previous commit:
#     $last_commit
# EOF
# git push
